fixing tests

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -26,12 +26,16 @@ jobs:
       id: find
       uses: ./
       with:
-        string: Search is performed in this string. GA-250 will be found
+        string: Search is performed in this string. FIND-1 will be found
 
     - name: Find Issue Key
       uses: ./
       with:
         string: ${{ github.event.ref }} will search in branch name
+
+    - name: error if missing issue
+      if: ${{ steps.find.outputs.issue == '' }}
+      run: echo "Issue not found" && exit 1
 
     - name: Find issue info
       run: echo "Issue ${{ steps.find.outputs.issue }} was found"
